### ISSUE TITLE
Build does not work any more

### ISSUE THREAD

**Issue by Tokanhaku** [facelessuser/MarkdownPreview#10]
![](https://cl.ly/rbo9/Screen%20Shot%202018-05-16%20at%2013.18.38.png)

`browser`, `clipboard`, `sublime` in the `build_action` still work. but it does't save a new html file when I build a .md file with `build`.

![](https://cl.ly/rcMY/Screen%20Shot%202018-05-16%20at%2013.28.31.png)

Can you help?

**Comment by facelessuser** [comment]
Fixed.  Thanks!
