### ISSUE TITLE
how to use mathjax in git lab ?

### ISSUE THREAD

**Issue by weidongzhou1994** [facelessuser/MarkdownPreview#104]
I want to display math in git lab or footnote in python markdown, but I don't konw the methods, so what can I do.

**Comment by facelessuser** [comment]
> or footnote in python markdown

Footnotes should be enabled by default. Please reference the footnote extension's documentation on how to use: https://python-markdown.github.io/extensions/footnotes/.

> I want to display math in git lab

You would want to references GitLab's Markdown documentation: https://docs.gitlab.com/ee/user/markdown.html#math.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by facelessuser** [comment]
Closing as there is no actionable item.
