### ISSUE TITLE
TOC doesn't show header which includes formulas correctly

### ISSUE THREAD

**Issue by JingwangLi** [facelessuser/MarkdownPreview#107]
I found TOC doesn't show header which includes formulas correctly even the header is normal in the body.
![image](https://user-images.githubusercontent.com/29228612/72410217-de2de200-37a2-11ea-80da-5c9437ec8d59.png)
![image](https://user-images.githubusercontent.com/29228612/72410231-e4bc5980-37a2-11ea-9825-4608ca300898.png)

I'm not sure if it's suitable to put this issue here because I don't know if Markdown Preview has altered it or just simply call it. If not, please tell me, I'll close it here and put it in Python-Markdown.

**Comment by facelessuser** [comment]
We do not alter TOC. It is what it is.
