### ISSUE TITLE
Custom path_tempfile does not work

### ISSUE THREAD

**Issue by bryankato** [facelessuser/MarkdownPreview#108]
I've tried defining a custom "path_tempfile" ie. "path_tempfile": "build". This creates an empty "build" folder, but the build file is created in the existing folder containing the .md file.

**Comment by facelessuser** [comment]
@bryankato , `path_tempfile` is where preview builds go. Are you using the preview command? This seems to work just fine for me.

**Comment by bryankato** [comment]
I'm using the build command, "cmd + b" in OSX. I wasn't able to find a preview command, am I missing something?

**Comment by facelessuser** [comment]
Please read the documentation on previewing: https://facelessuser.github.io/MarkdownPreview/usage/#to-preview

**Comment by bryankato** [comment]
Thanks! I changed "build_action" from "build" to "browser" and it's working as expected now.

**Comment by facelessuser** [comment]
No problem

@gir-bot remove S: triage
@gir-bot add T: support
