### ISSUE TITLE
Markdown syntax inside MathJax delimiter

### ISSUE THREAD

**Issue by ypsy** [facelessuser/MarkdownPreview#110]
Hi,
I noticed that when using underscores (subscript in MathML) following a closing curly brace inside MathJax delimiters (which is a dollar sign for me), Sublime Text still interprets them as Markdown Syntax, thus displaying the following text as emphasized. HTML is rendered as expected. It's a bit annoying in the editor though.

![Bildschirmfoto vom 2020-02-20 17-37-46](https://user-images.githubusercontent.com/1438229/74958104-6174d000-5400-11ea-9139-8223297497eb.png)

Thanks in advance!

**Comment by facelessuser** [comment]
Markdown Preview does not have a custom Syntax Highlighter. We only provide rendering, not highlighting.

@gir-bot remove S: triage
@gir-bot add S: wontfix

**Comment by ypsy** [comment]
Oh I'm very sorry, I thought I remembered that Sublime itself did not provide any Markdown Highlighting and MarkdownPreview added it, which was wrong.

In case anybody faces the same problem: The "Markdown Extended" package provides a Markdown highlighter that recognizes the dollar signs.

Sorry again and thanks for your quick reply.
