### ISSUE TITLE
Relative image path issue

### ISSUE THREAD

**Issue by petko10** [facelessuser/MarkdownPreview#114]
Hello, I've added the options:
```
{
    "image_path_conversion": "relative",
    "file_path_conversion": "relative",
}
```
to the user config, but the extension outputs incorrect paths like `../home/user/projects/dummy_project/media/picture.png` while the markdown file is a README.md in `/home/user/projects/dummy_project/`, and the picture is defined as `![picture](media/picture.png)`

**Comment by facelessuser** [comment]
Please post full user settings (do **not** include any github auth tokens or info you view as sensitive).

Just an FYI, it is currently working for me with no issues.

**Comment by petko10** [comment]
I'm so sorry to have bothered you. I'd overlooked the URL and missed a folder. It was `src/media/picture.png`. And I didn't how paths like `../absolute/path` would have meaning, but the html preview is stored in /tmp, so that makes sense..
Thanks for taking the time to maintain this great extension.

**Comment by facelessuser** [comment]
No problem, glad you figured it out
