### ISSUE TITLE
Make it compatible with VS Code

### ISSUE THREAD

**Issue by tempusthales** [facelessuser/MarkdownPreview#118]
Could you make this script compatible with VS Code?

**Comment by facelessuser** [comment]
I'm not sure what's being suggested here. Are you requesting a VSCode plugin?

**Comment by facelessuser** [comment]
I'm assuming you are asking for this to work in VSCode, and since I am not a user of VSCode, I will not be offering such support. I do not have the time to offer support for a platform I am not invested in.

@gir-bot add S: wontfix
