### ISSUE TITLE
GitHub dark theme

### ISSUE THREAD

**Issue by npanuhin** [facelessuser/MarkdownPreview#119]
Hello!
A few days ago, GitHub released the **dark theme**!

Since this plugin is often used to preview the result before publishing it, it would be very handy if a dark theme was implemented here as well.

I opened the `css` folder and found that you have your own CSS files to style the GitHub API output. So creating the second optional `css/github_dark.css` file is just a matter of time, am I right? :wink:

**Comment by facelessuser** [comment]
Is certainly possible. Is have to look into how difficult this would be. I know we sourced most of the CSS from a repo that scraped the store from GitHub, so if they have something that includes the dark theme as well, we could leverage that.

**Comment by npanuhin** [comment]
Okay, got it. Which repository are you talking about?

**Comment by facelessuser** [comment]
IIRC: https://github.com/sindresorhus/github-markdown-css

**Comment by facelessuser** [comment]
We add a little on top of it I think, but overall, we used what was provided in that repo.

**Comment by Mohammad9760** [comment]
Hi... so I also would like to build md to html with a darktheme.
any progress here?

**Comment by facelessuser** [comment]
TBH, it's been a pretty low priority, and it slipped my mind. It's probably worth looking into again though.

**Comment by facelessuser** [comment]
I am finally getting around to this. It will respond to your system theme.

<img width="689" alt="Screenshot 2024-01-14 at 1 21 34 PM" src="https://github.com/facelessuser/MarkdownPreview/assets/1055125/60b9a8c2-ecba-4cff-95e7-1209997b197a">

**Comment by facelessuser** [comment]
Closed by: https://github.com/facelessuser/MarkdownPreview/commit/d5376c64b2065c95f90e8f614527f5ae4c23e39c

**Comment by npanuhin** [comment]
It works great, thank you! Maybe we can also add a manually configurable option in the package settings, or even a switch/toggle button in the rendered HTML that toggles between light/dark modes? Changing the entire browser theme back and forth just to test how my markdown page looks in different modes is kinda overkill)

**Comment by facelessuser** [comment]
You can open a new issue and I can look into some solution.
