### ISSUE TITLE
Code-block backtick snippet

### ISSUE THREAD

**Issue by roguephysicist** [facelessuser/MarkdownPreview#132]
I recently updated to Sublime Text 4 and refreshed my Markdown Preview configuration file; I had been using the same one for years. Unfortunately this has brought about a change that I would rather do without:

When I want to start a code-block and I type two backticks (` `` `), I immediately get prompted with a snippet that autocompletes the third backtick and displays `language` for selecting the highlighting. It also writes the ending ` ``` ` backticks.

I have looked through the config file and the documentation, but simply cannot find any way to turn this feature off. Can you please tell me what option I need to add to my user settings in order to accomplish this?

BTW, thank you for the excellent work on this package. I have been using it for around 7 years and it is an essential part of my workflow.

**Comment by facelessuser** [comment]
Yeah, this package just previews Markdown, it doesn't add any snippets. I believe the snippet is built into the latest Sublime Markdown package, so you may want to take it up with Sublime HQ.

Obviously, as there is nothing for us to fix here, this is a `wontfix`.

@gir-bot remove S: triage
@gir-bot add S: wontfix
