### ISSUE TITLE
Add How to use in the README or in the documentation

### ISSUE THREAD

**Issue by cainotis** [facelessuser/MarkdownPreview#135]
this package was no section saying how to use in the README making difficult to new user to use, and it shouldn't  be to much work writing a resume about how to start using it.

**Comment by facelessuser** [comment]
Please look at the documentation that is linked on the README. Everything you need is there: https://facelessuser.github.io/MarkdownPreview/usage/#to-preview.

The README provides a description of what the project is and redirects the user to the official docs, I have no plans to change that. With that said, if you find the documentation lacking in some way, feel free to provide a pull request

@gir-bot  remove T: triage
