### ISSUE TITLE
Outdated [toc] link destination

### ISSUE THREAD

**Issue by grgbnc** [facelessuser/MarkdownPreview#136]
The outdated link destination of the [`[toc]` link reference definition](https://github.com/facelessuser/MarkdownPreview/blob/master/docs/src/markdown/_snippets/refs.txt#L23) should be updated to <https://python-markdown.github.io/extensions/toc/>

**Comment by facelessuser** [comment]
Thanks for letting me know!

@gir-bot remove S: triage
@gir-bot add T: maintenance, C: docs
