### ISSUE TITLE
Browser option doesn't work on macOS Big Sur with Choosy

### ISSUE THREAD

**Issue by revolter** [facelessuser/MarkdownPreview#137]
I'm using [Choosy](https://www.choosyosx.com/) as the default browser, but this extension always opens the preview in Safari.

This happens even if I set

```json
{
    "browser": "/Applications/Choosy.app"
}
```

or

```json
{
    "browser": "/Applications/Choosy.app/Contents/MacOS/Choosy"
}
```

**Comment by facelessuser** [comment]
I'll have to take a look this weekend. I'm unaware of anything that prevents a specific browser from opening, but I'll verify again the setting on macOS.

**Comment by revolter** [comment]
True, but it was made specifically to act as a browser, even if it's not one. This means that any link from any app opens in Choosy for me 🤔

**Comment by facelessuser** [comment]
I understand, but generally, I want to test if the feature works, not special, abnormal cases that require special workarounds. It would be up to the user to come back here with clear details as to what this abnormal cases requires.

If the feature launches normal browsers fine, but not choosy, then what I would ask of you is what does choosy require extra? I'm not sure I have time to debug odd "sort of browser, but not really cases".

So, my focus will most likely be ensuring the feature generally works, and if not, fixing the problem, and for users to provide me with additional, required details for special cases if we'd like to get them working.

I'll let you know what I find soon.
