### ISSUE TITLE
Preview File's References Too

### ISSUE THREAD

**Issue by STSMHQ** [facelessuser/MarkdownPreview#139]
I would like to know if it's possible to preview the file's references too. For example, if I've in a file:

```markdown
[MyOtherFile](./myOtherfile.md]
```

Is it possible to preview the file and `myOtherFile` as well?! Because, right now the preview references the file correctly but it stands in Markdown language. I would like to have it HTML language as the main file.

Regards,
**STSM**

**Comment by facelessuser** [comment]
MarkdownPreview will simply render the file you tell it to from Sublime Text in your browser. It does not run a backend server, so clicking paths in an HTML server are **not** sent to a server running in Sublime to request a new page to be rendered.

This is just something we don't support. I have no plans at this time to essentially create a running server that watches all of your project's Mardown files, building them dynamically when an HTTP request is received from a browser.

@gir-bot remove S: triage
@gir-bot add S: wontfix

**Comment by STSMHQ** [comment]
> MarkdownPreview will simply render the file you tell it to from Sublime Text in your browser. It does not run a backend server, so clicking paths in an HTML server are **not** sent to a server running in Sublime to request a new page to be rendered.
> 
> This is just something we don't support. I have no plans at this time to essentially create a running server that watches all of your project's Mardown files, building them dynamically when an HTTP request is received from a browser.
> 
> @gir-bot remove S: triage @gir-bot add S: wontfix

I see. Thanks anyway for the answer. Keep the great work :3
