### ISSUE TITLE
MathJax is not showing up

### ISSUE THREAD

**Issue by kctong529** [facelessuser/MarkdownPreview#14]
I'm not sure why this is happening, as I haven't changed those .md files in two months, and haven't modified the Package Settings since then. The last time I tried, everything worked fine, where I could preview all `$$display math mode$$` and `$$\begin{aligned} \end{aligned}$$`. But today when I preview the same thing again, those equations are not showing up as expected. They are treated as any other normal text strings, while I have `"enable_mathjax": true,` in my Package User Settings. I've updated the Sublime Text version afterwards, but no difference. My machine is MacOS High Sierra 10.13.3. Thank you.

**Comment by facelessuser** [comment]
Please see https://github.com/facelessuser/MarkdownPreview/issues/12 which answers your question. The recommended solution will probably be updated soon with a less generic solution soon, but that thread should help you get rolling.

**Comment by facelessuser** [comment]
A better default MathJax config is provided that targets just `arithmatex` classes. This will prevent some unexpected issues.  Documentation has also been updated to be more clear. Closing this issue.
