### ISSUE TITLE
Does this work with Sublime Text 4126?

### ISSUE THREAD

**Issue by AndyZBell** [facelessuser/MarkdownPreview#140]
I've installed it. Then I restarted ST.

Then I create a markdown (.md) document and write some simple markdown.

I then try the preview to browser - nothing happens. I try to copy the preview to the clipboard. Nothing is copied to the clipboard...

No error messages - just silence.

Andy

**Comment by facelessuser** [comment]
Yes, it works just fine. You'd have to check the console to see if there are errors and pay them if you find any. You also would need to provide the exact steps you are performing. Lastly, if you've changed any settings, you'd have to post them as well.

Unfortunately, without any information, I cannot debug.

**Comment by facelessuser** [comment]
As the conversation has stalled, I'm closing this as stale.
