### ISSUE TITLE
How to use nested lists without calling github API?

### ISSUE THREAD

**Issue by jfcherng** [facelessuser/MarkdownPreview#141]
I think this is frequently used but no one asked before... I must miss something.

```md
* parent
  * child
```

* parent
  * child

However, the `markdown` parser seems to ignore the indentation and generates a flatten list.

**Comment by facelessuser** [comment]
Python Markdown requires 4 spaces for nested lists.

**Comment by jfcherng** [comment]
> Python Markdown requires 4 spaces for nested lists.

This is it. Thanks :D
