### ISSUE TITLE
Red line appearing in output

### ISSUE THREAD

**Issue by sarbjitbilling** [facelessuser/MarkdownPreview#144]
Hi - Is it possible to remove the nasty red line that appears on bad markup.  I have some files I have no control over and I'd prefer not to see this warning.  Thanks

**Comment by facelessuser** [comment]
What red line?

**Comment by sarbjitbilling** [comment]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/5271104/169036917-7c29361f-1551-4c2f-a463-0a0f6b1adde8.png">

I appreciate the above is invalid markdown.  But could be turned off, or made less striking.

**Comment by facelessuser** [comment]
You are confusing this package with another. We do not provide syntax highlighting for Markdown in Sublime Text. We generate HTML from Markdown and open it in a browser.

**Comment by sarbjitbilling** [comment]
Thanks.  Sorry for the confusion.
