### ISSUE TITLE
GitLab preview authentication token expired

### ISSUE THREAD

**Issue by JoyBrad** [facelessuser/MarkdownPreview#158]

**Comment by facelessuser** [comment]
You need to generate yourself a non-expired token then.

**Comment by JoyBrad** [comment]
Thanks

**Comment by jaluc** [comment]
Just in case anyone else runs into this issue:
1. You'll need to create a personal access token with the `api` scope. It appears that other scopes will result in a 403 error "insufficient scope".
2. Then you'll need to go to Sublime Text's `Preferences/Package Settings/Markdown Preview/Settings` and save it as such:
```json
{
"gitlab_personal_token": "your-new-personal-and-secret-access-token-goes-here",
}
```
