### ISSUE TITLE
Black code block 

### ISSUE THREAD

**Issue by ape660** [facelessuser/MarkdownPreview#165]
Is it possible to change a block of code to a black background ? Like
![图片](https://github.com/facelessuser/MarkdownPreview/assets/48158080/54de6816-cb69-4fb4-aabb-ccd0d05930b8)
How do I set it up？

**Comment by facelessuser** [comment]
I'm assuming you are using the Python Markdown parser option, so you'd have to configure the Pygments options: https://facelessuser.github.io/MarkdownPreview/usage/?h=pygments#configuring-pygments.

**Comment by ape660** [comment]
I am using the Python Markdown parser. I try to set `pygments_style` to a dark style provided by pygments. But no html file generate. I try one-dark, solarized-dark, github-dark and so on. No html generate! I cant change the code block style  into dark. 
my setting 
```
        {
             "pymdownx.highlight": {
                "noclasses": true,
                "linenums": true,
                "pygments_style": "github-dark"

            }
        },
```
I got styles  provided by Pygments
```python
from pygments.styles import STYLE_MAP
STYLE_MAP.keys()
```
the output
```
dict_keys(['default', 'emacs', 'friendly', 'friendly_grayscale', 'colorful', 'autumn', 'murphy', 'manni', 'material', 'monokai', 'perldoc', 'pastie', 'borland', 'trac', 'native', 'fruity', 'bw', 'vim', 'vs', 'tango', 'rrt', 'xcode', 'igor', 'paraiso-light', 'paraiso-dark', 'lovelace', 'algol', 'algol_nu', 'arduino', 'rainbow_dash', 'abap', 'solarized-dark', 'solarized-light', 'sas', 'staroffice', 'stata', 'stata-light', 'stata-dark', 'inkpot', 'zenburn', 'gruvbox-dark', 'gruvbox-light', 'dracula', 'one-dark', 'lilypond', 'nord', 'nord-darker', 'github-dark'])
```
But most **dark** themes are not effective(no html output).

Did I do something wrong? I think i need more tips.

**Comment by ape660** [comment]
Thank you! you are too kind.

**Comment by facelessuser** [comment]
Generally, things will be working better in the next version. If you require additional styling tweaks, you may have to use your own overrides via https://facelessuser.github.io/MarkdownPreview/usage/#including-css.
