### ISSUE TITLE
Documentation Rendring Issue in Mermaid UML Support Section

### ISSUE THREAD

**Issue by RoyiAvital** [facelessuser/MarkdownPreview#166]
The [Mermaid UML Support](https://facelessuser.github.io/MarkdownPreview/extras/#mermaid-uml-support) section has rendering bug:

<img width="735" alt="image" src="https://github.com/facelessuser/MarkdownPreview/assets/7347975/06e419db-24b0-41e4-9e3c-2f3e710bf983">

Something with the code ticks.

**Comment by facelessuser** [comment]
This seems to have already been fixed but never deployed. The next release will fix this issue.

**Comment by RoyiAvital** [comment]
I had a recollection we have talked about it, yet I searched for an issue but did not find :-).
