### ISSUE TITLE
anchor link is not working 

### ISSUE THREAD

**Issue by itboone** [facelessuser/MarkdownPreview#167]
It should be possible to use cros-reference to link information inside a document.

For example：clicking on the sub directory should redirect to the corresponding title, but it is not working.

## Title
* [sub1](#sub1)
* [sub2](#sub2)
* [sub3](#sub3)

### sub1

_**Take me to [pookie](#pookie)**_

it should be the correct markdown syntax to jump to the anchor point named pookie.

### sub2

To insert an anchor point of that name use HTML:

`<a id="pookie">I'm pookie</a>`

### sub3

Markdown doesn't seem to mind where you put the anchor point. A useful place to put it is in a header.

This feature does not work in markdown-preview.

---

> **<a id="pookie">I'm pookie</a>**
---

**Comment by facelessuser** [comment]
I'm not sure I understand the claim "not working". You would need to provide more information. You can see in this gif that I  used Markdown Preview to generate the HTML from the Markdown you posted and the references work fine.

![pookie](https://github.com/facelessuser/MarkdownPreview/assets/1055125/3d20954c-ebc2-42ed-b24e-7dd6fcb494d7)

**Comment by facelessuser** [comment]
You did not mention you were using GitHub Markdown. Please read this: https://facelessuser.github.io/MarkdownPreview/usage/?h=github#parsing-github-flavored-markdown. 

You'll want to enable `github_inject_header_ids`.
