### ISSUE TITLE
Video content cannot be displayed

### ISSUE THREAD

**Issue by zhouxinghong** [facelessuser/MarkdownPreview#173]
Video content cannot be displayed

When previewing md files in Chrome browser in github mode, the video content cannot be displayed.
```
<video controls muted preload="auto" src="https://xxxxxxx.mp4"> 
</video>
```
Windows 10 19044
Chrome is up to date
Version 119.0.6045.124 (Official Build) (64-bit)
VERSION 2.4.3

**Comment by zhouxinghong** [comment]
![image](https://github.com/facelessuser/MarkdownPreview/assets/54253524/626bda50-2504-4119-9f26-4a0989e3de4e)

**Comment by zhouxinghong** [comment]
Hope this bugs can be fixed, thank you very much! 😜

**Comment by facelessuser** [comment]
This is probably because GitHub strips out the Video tags. If you use the Markdown option, it works fine. We don't do anything special with Video tags, so if they are not working, it is because of what GitHub is doing to them during parsing.

**Comment by facelessuser** [comment]
I verified locally using `markdown` for `github_mode`, it seems to strip the video tag and the `src`, and in `gfm` mode it removes the `src`. This is all GitHub's doing and is out of our control.
