### ISSUE TITLE
HTML preview file not found

### ISSUE THREAD

**Issue by andanders** [facelessuser/MarkdownPreview#182]
## Problem
When I try to preview my markdown in browser, the browser fails to show the file.

## Actions to reproduce
In sublime -> Preview in Browser -> markdown -> <enter>

Firefox opens and shows the error:
> File not found
> Firefox can’t find the file at /tmp/41.html.
> 

## System details
OS Ubuntu 22.04 LST
Sublime build 4169
MarkdownPreview version 2.5.0
Firefox 127.0.2 (64 bit)

**Comment by facelessuser** [comment]
@andanders it is likely this is the issue you need to read through https://github.com/facelessuser/MarkdownPreview/issues/170. Since on Linux, Firefox will store things in an unexpected temp location, you may need to manually configure your temp path.

**Comment by facelessuser** [comment]
As I've heard no response for two weeks, closing this issue as stale.
