### ISSUE TITLE
missing newline before list behaves different in github and markdown preview

### ISSUE THREAD

**Issue by joernhees** [facelessuser/MarkdownPreview#186]
i'm used to github flavored markdown and noticed that 

```
no newline after this
- bullet
- bullet
```

also rendering here as:

no newline after this
- bullet
- bullet

will render differently in markdown preview when i select markdown (getting confused, packing all in one line) instead of the online github parser.

After reading around a bit, i now seem to understand that this is the official spec saying "but nooo, you need a newline there, otherwise no one could know what you mean", but i somehow find the github interpretation of this much more intuitive 🤷‍♂️.

Is there a simple way to fix this difference via configs of MarkdownPreview? (So i'd love to use the local markdown parser, but make it behave slightly more like the github one wrt. the list parsing.)

I've found https://github.com/facelessuser/MarkdownPreview/issues/102 but it seems to do something else (and change a lot more).

**Comment by facelessuser** [comment]
That's just how Python Markdown works. If you want it to parse just like GitHub does, you need to use the GitHub online parser. I think it is enabled by default, so you just have to select it. Configuration for the GitHub parser is documented here: https://facelessuser.github.io/MarkdownPreview/usage/?h=github#parsing-github-flavored-markdown.

It assumes `github` is specified in the parsers: https://facelessuser.github.io/MarkdownPreview/usage/?h=github#enabling-other-external-markdown-parsers.

**Comment by joernhees** [comment]
My question is more if there's a simple fix/setting/workaround for the local "markdown" parser, which already seems quite adapted to give a more github flavored markdown like feeling, just not wrt. these newlines...

**Comment by facelessuser** [comment]
What I'm saying is that this behavior is fundamental to how Python Markdown works. Yes, I could alter the behavior by modifying the Python Markdown parser, but I'm not going to do that. Python Markdown is an old-school parser, GitHub is a CommonMark parser. If you need 1:1 functionality with GitHub, the best choice is to use GitHub's parser.
