### ISSUE TITLE
add GitLab support

### ISSUE THREAD

**Issue by hadisfr** [facelessuser/MarkdownPreview#22]
Hi!

[GitLab](gitlab.com) has offer private repos in free plans, too. For some reasons including this one, some people (including me, myself :-" ) prefer it to [GitHub](GitHub.com). Also, recent purchase of GitHub by Microsoft make many people migrate to GitLab.

GitLab has got a [GitLab Flavored Markdown (GFM)](https://docs.gitlab.com/ee/user/markdown.html), too. There's some minor differences between GitLab's GFM and GitHub's GFM, and, also, the page styles are different.

Also, GitLab provides a [Markdown API](https://docs.gitlab.com/ee/api/markdown.html) rather similar to GitHub's one.

I think it's a good idea to add support for GitLab. Maybe I can help a little myself.

**Comment by hadisfr** [comment]
#### an example of differences between GFMs
###### GitHub
```markdown
>>>
If you paste a message from somewhere else

that

spans

multiple lines,

you can quote that without having to manually prepend `>` to every line!
>>>
```
###### GitLab
<img width="561" alt="image" src="https://user-images.githubusercontent.com/24562441/42067045-8adfd18c-7b59-11e8-9887-52e32bb83836.png">

**Comment by facelessuser** [comment]
I'm not against gitlab API support. I see we have a pull request, so I'll evaluate that when I have a chance.

**Comment by ipkpjersi** [comment]
I would be extremely happy to see this make it in, I have wanted this feature for a while. :D

**Comment by facelessuser** [comment]
Ref #23

**Comment by facelessuser** [comment]
@hadisfr, Finally merged 🙂 .

**Comment by hadisfr** [comment]
Thank you. :D

**Comment by facelessuser** [comment]
I will most likely make a release later today.
