### ISSUE TITLE
MathJax dont work 

### ISSUE THREAD

**Issue by WhiteDLee** [facelessuser/MarkdownPreview#25]
MathJax dont work, even I add "enable_mathjax": true in settings

**Comment by WhiteDLee** [comment]
I have solved it.

Add
	"js": [
        "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js",
        "res://MarkdownPreview/js/math_config.js",
        "https://cdn.jsdelivr.net/npm/katex@0.10.0-alpha/dist/katex.min.js",
        "res://MarkdownPreview/js/katex_config.js"
    ],
    "markdown_extensions": {
        "pymdownx.arithmatex": {
            "generic": true
        }
    }
in the settings.

**Comment by facelessuser** [comment]
You don't need MathJax and KaTeX config and scripts, you should pick one. But glad you figured out how to get things working.

**Comment by WhiteDLee** [comment]
Thank you for your answer! I watch [Markdown Preview Documentation](https://facelessuser.github.io/MarkdownPreview/) again the delete the KaTeX config and scripts as you said.
But when I directly add these code in the settings, some other problems encounter. That is all other extended functions don't work, like [TOC]. It‘s terrible! So I try to add the latter half of codes into "pymdownx.superfences", like this:
"pymdownx.superfences",  // Nested fences and UML support
        {
            "pymdownx.magiclink": {   // Auto linkify URLs and email addresses
                "repo_url_shortener": true,
                "repo_url_shorthand": true
            },
            "pymdownx.arithmatex": 
            {
                "generic": true
            }
        },
So lucky! It works well, although I don't know why. HAHAHAHAHA!
Thanks again for your reply!
