### ISSUE TITLE
MarkdownPreview on command line

### ISSUE THREAD

**Issue by natanfelles** [facelessuser/MarkdownPreview#26]
Hi, very thanks for this awesome package!

A python newbie question: 

**Is possible run MarkdownPreview in the terminal?**

If yes: How to?

If not: What do you think about adapt it?

Thank you!

**Comment by facelessuser** [comment]
What do you mean in the terminal, you mean outside of Sublime in a terminal?

**Comment by natanfelles** [comment]
Yes. Some command like pandoc `pandoc --from markdown_strict --to html5 filename.md`.

But with the MarkdownPreview styles, Pygments, etc...

**Comment by facelessuser** [comment]
MarkdownPreview currently is configured to be used in the Sublime environment.  Yes you could technically run `subl` and give it a command to run, but that would open up the Sublime editor.  MarkdownPreview would have to be reworked to run outside of the Sublime environment.  Is it possible to rework it? Yes, but that is not the intention of this plugin.

**Comment by natanfelles** [comment]
OK. Very thanks!
