### ISSUE TITLE
Sublime Keeps Disabling the Package

### ISSUE THREAD

**Issue by jwatsonlegalserver** [facelessuser/MarkdownPreview#29]
Every time I reboot, the ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings file is updated by something that adds MarkdownPreview to the ignore list.

```json
"ignored_packages":
	[
		"MarkdownPreview",
		"SublimeLinter",
		"Vintage"
	],
```
I remove the line, save the file, and things are great until I shut down. Then, upon boot, the file is against changed. Would you happen to know what might be causing this?

Thank you,
Jim Watson

**Comment by facelessuser** [comment]
It might be package control.  When it goes to update a package, it disables it first, updates it, then reenables it.  But if something goes wrong, it will not update and sometimes leave the package in disabled.  That is my guess to what is happening, but I am afraid I can't offer anything more that this guess based on the information you've provided.

**Comment by facelessuser** [comment]
As no further info had been provided, I'm closing this issue.
