### ISSUE TITLE
Per parser css and js

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/MarkdownPreview#30]
It has become more clear to me that it may be of benefit to have per parser `css` and `js`.  For now, if `css` and `js` is an array as it has always been, it will be used for any parser, but if it is a dict (with parsers as the keys, then it will look at the value associated with that key as the list of `css` and `js` for that parser.

**Comment by RoyiAvital** [comment]
By the way, why the CrtitcMarkup CSS is missing from GitHub CSS?

Moreover, could the default CSS for CriticMarkup be like in https://github.com/facelessuser/pymdown-extensions/blame/260239559dfdb0ebc957faa41a61ce7578d33a78/docs/src/markdown/extensions/critic.md#L116 ?

**Comment by facelessuser** [comment]
@RoyiAvital, your question is not related to the issue "Per parser css and js".  Please open a new issue if you have a question.  Thanks.

**Comment by facelessuser** [comment]
Resolved via #37
