### ISSUE TITLE
Manual Table of Contents

### ISSUE THREAD

**Issue by hadisfr** [facelessuser/MarkdownPreview#32]
GitHub doesn't render `[TOC]` as I know. It may be a good idea to use [naokazuterada/MarkdownTOC](https://github.com/naokazuterada/MarkdownTOC) as a dependency or write some functions from scratch to add ability to create a ToC manually in sublime. 🤔

**Comment by facelessuser** [comment]
If people wish to use MarkdownToc, there is nothing currently prohibiting them.  I would encourage users to evaluate it and see if it fits there needs.  I suspect that its header id generation may not match every implementations methodology, but I'll leave it up to the user to discover if it fits their needs.

It would probably make more sense to scan header ids as a post processes and locate and replace a specific marker.  I'm personally not interested in using MarkdownToc, and as far as GitHub is concerned, I'd prefer it matches what GitHub currently does, and it doesn't generate TOCs, so I'm not generally concerned with this feature.  I would possibly consider it as a post process, but I have no control over something like MarkdownTOC.
