### ISSUE TITLE
State ST version compatibility

### ISSUE THREAD

**Issue by kerstin** [facelessuser/MarkdownPreview#36]
I think it'd make sense to include info on how the continuation of this plugin only supports ST3.

Right now there is no mention of this in the README nor the repository description. But other repos linking to this one, including the original which it was forked from (which has ST2/3 in its description), don't make any mention of this either.

I also saw there was already at least one issue (#9) where the compatibility wasn't clear to the asker.

**Comment by facelessuser** [comment]
I'm fine with this being added. Pull requests are also welcome!
