### ISSUE TITLE
Emoji vertical aligment wrong

### ISSUE THREAD

**Issue by akaleeroy** [facelessuser/MarkdownPreview#4]
Emoji `align="absmiddle"` doesn't look right. :point_down: 

![Emoji less-then-ideal vertical alignment](https://user-images.githubusercontent.com/4068718/39957195-793d50f8-55f7-11e8-8ab7-b0c4c37c476f.png)

Maybe `align="base"` is better?

**Comment by facelessuser** [comment]
I'll take a look again and see if some adjustments are needed.

**Comment by facelessuser** [comment]
If we use `align="base"`, the emoji will no longer be centred, but be at the base of the line, and the top of the emoji will push the line above it up higher, creating a larger gap between the line it is on and the line above it. You'd either need to increase size of text or decrease size of emoji.  The way lines of text work, is that if they are bigger that the normal letter, they hang lower, like the bottom of the letter`g` etc.  The current convention makes sense to me. Using `base` forces  the images to bleed into the line above, and seems wrong.

**Comment by facelessuser** [comment]
What we are doing seems consistent with the look I see everywhere else.  You can actually set your alignment in the settings if you don't like the default.  You can also override the default CSS if you like, so all this can be configured to your liking if there is a difference of opinion. Personally, I think the behavior we are seeing is exactly what I would expect. If anything, a case could be made that text size vs emoji size should be adjusted for a better ratio.

I am open to different defaults, but there would have to be a reasonable case made for the suggestion.  Unfortunately, `align="base"` introduces some side effects I am not willing to accept.
