### ISSUE TITLE
Trying to preview markdown 

### ISSUE THREAD

**Issue by jcaputo79** [facelessuser/MarkdownPreview#43]
Hi there,

When trying to preview my markdown, it actually triggers a startup of my parallels desktop vm.  It just started doing this in the last couple of weeks.  It worked correctly before.  Any idea as to what may have happened?

**Comment by facelessuser** [comment]
If you could tell me what you are doing, that may help. Are you running the commands directly, using a shortcut, etc. Maybe something is overriding your shortcut, I don't know. I need more info.

**Comment by facelessuser** [comment]
Close as no new information has been provided.
