### ISSUE TITLE
Do not show the entire changelog for each update

### ISSUE THREAD

**Issue by FichteFoll** [facelessuser/MarkdownPreview#46]
Please do not specify `docs/src/markdown/changes.md` for each update in `messages.json`. It will cause the *entire* changelog to be displayed for *each* version that was skipped in addition to the newest update. Package Control automatically only shows changelogs for versions since the latest update. Having this *huge* changelog displayed for each update, possibly weekly, is just annoying and unnecessary.

**Comment by facelessuser** [comment]
Shown every update is the convention the original author used. I plan on only showing a message for major releases and suggest users see changelog if they want to know more. Just haven't done it yet.

**Comment by FichteFoll** [comment]
(I know you follow this policy for other packages, but I was going through a couple updated packages after a 2-week vacation and finally created some issues for offenders – with the same text.)

**Comment by facelessuser** [comment]
I had already moved to this convention.  Unfortunately I had a number of non-bug fix releases in a row, so I will close this issue as it is a non-issue.
