### ISSUE TITLE
Viewport scaling in default HTML export

### ISSUE THREAD

**Issue by akaleeroy** [facelessuser/MarkdownPreview#47]
I propose adding `<meta name="viewport" content="width=device-width, initial-scale=1">` to [markdown_preview.py#L569](https://github.com/facelessuser/MarkdownPreview/blob/master/markdown_preview.py#L569) for appropriate rendering on mobile by default

**Comment by akaleeroy** [comment]
## HTML Template Workaround

`Sublime Text\Data\Packages\User\markdownpreview-template.html`
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {{ HEAD }}
  </head>
  <body>
    <article class="markdown-body">
      {{ BODY }}
    </article>
  </body>
</html>
```

`Sublime Text\Data\Packages\User\MarkdownPreview.sublime-settings`
```json
{
  "html_template": "C:\\Program Files\\Sublime Text\\Data\\Packages\\User\\markdownpreview-template.html"
}
```

**Comment by facelessuser** [comment]
Yeah, I'm think I'm fine with this.  Pull requests are also welcome.
