### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by catamphetamine** [facelessuser/MarkdownPreview#52]
It doesn't say anything in the docs.
So I installed it and then what?

**Comment by catamphetamine** [comment]
I see, so a user needs to push Ctrl + Shift + P, then enter "Markdown Preview: Preview in Browser".
You should add that to the docs.

**Comment by hadisfr** [comment]
There's sth in the documentations already: https://facelessuser.github.io/MarkdownPreview/usage/. :D

**Comment by facelessuser** [comment]
Yup, the readme at the project root specifically points to the document site for more details.  I'll consider this answered.
