### ISSUE TITLE
Add an option to make line automatically wrapped in code blocks

### ISSUE THREAD

**Issue by Puccet** [facelessuser/MarkdownPreview#54]
It would be nice to have an option to have the exported HTML with code block to wrap lines so the user does not have to scroll to read the content, it also make the generated html more suitable for printing and PDF export.

**Comment by facelessuser** [comment]
You are free to provide your own template with your own CSS. I see no reason to add an option for this. 
 Also, if you enable line numbers, wrapping doesn't work so well due to the way Pygments does line numbers.  I would look into providing your own custom CSS.
