### ISSUE TITLE
Tables not rendering when using the markdown parser

### ISSUE THREAD

**Issue by Moonire** [facelessuser/MarkdownPreview#55]
When I use 'markdown' as the parser for my preview, the tables are systematically rendered as simple text. where as the same tables get rendered neatly with both github and gitlab parsers.

Input:
First  Header  | Second Header
  ------------- | -------------
Content Cell  | Content Cell 
Content Cell  | Content Cell

Output:
`First Header | Second Header ------------- | ------------- Content Cell | Content Cell Content Cell | Content Cell`

**Comment by facelessuser** [comment]
You would need to provide your setting and check the console for errors and post them if you find any. As far as I am aware, this is working fine. I will double check to make sure tomorrow, but if it is working, I'll need more info from you.

**Comment by hadisfr** [comment]
It works fine for me, too. I couldn't reproduce the problem.

**Comment by Moonire** [comment]
Ok so I checked my setting and they actually are the problem

`{    
    "js": {
    "markdown": [
        "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js",
        "res://MarkdownPreview/js/math_config.js"
        ]
    },

    "markdown_extensions": [
    {
        "pymdownx.arithmatex": {
            "generic": true,
        },
    }
    ],

}
`
When I delete these, the tables worked fine but I couldn't render any equation any more. I'd like to be able to do both. Also I tried to delete only one of the too but apparently both are needed for Latex rendering, but I think its the arithimatex part that's causing this.

**Comment by facelessuser** [comment]
The problem is that when you define Arithmatex, you **only** define Arithmatex. Try copying the default extension settings and **add** Arithmatex to that.
