### ISSUE TITLE
Multi-platform Settings Support

### ISSUE THREAD

**Issue by apfelchips** [facelessuser/MarkdownPreview#56]
Override/Extend settings made in the "default" `MarkdownPreview.sublime-settings` file with Platform specific options set inside:

`MarkdownPreview (OSX).sublime-settings`
`MarkdownPreview (Linux).sublime-settings`
`MarkdownPreview (Windows).sublime-settings`

This is the default behavior of all native .sublime-settings files and most 3rd party extensions also support this feature.

Thanks.

**Comment by facelessuser** [comment]
This is not the default for most 3rd party extensions. This is only default for what Sublime has implemented internally. Settings are loaded and managed by  Sublime's API. If the API is not recognizing platform specific plug-in settings and merging them automatically, then we do not support them either, and will not support them until at some future time when Sublime sees fit to implement this.
