### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by GildedHonour** [facelessuser/MarkdownPreview#58]
I've installed it. In the Command Pallete there's still nothing related to the plugin.

**Comment by facelessuser** [comment]
You'll have to read the documentation provided. See link in readme.  You may or may not need to restart Sublime after installing a plugin for it to load properly. See configuration guide to see that you have it configured properly. If you have errors in the console, please open a new issue with the error and any useful debug information.

As "How to use it?" is so vague, the best answer is to read the docs.

**Comment by GildedHonour** [comment]
No errors in the console.

**Comment by facelessuser** [comment]
Currently I've been given nothing to debug. If you have difficulty understanding something specifically in the documentation, or an example of what you are trying that isn't working, then I can possibly offer some guidance.
