### ISSUE TITLE
Package not installing on ST3

### ISSUE THREAD

**Issue by lrdegeest** [facelessuser/MarkdownPreview#63]
Working in ST3.1.1 Build 3176 for Mac 0S. Unable to install MarkdownPreview via "Package Control: Install Package". Nothing happens on my screen, and the package does not show up in `Library/Application Support/Sublime Text 3/Installed Packages`. What is going on?

**Comment by facelessuser** [comment]
You may have to take this up over at https://github.com/wbond/package_control/issues.

I simply provide the package. Package Control manages the distribution. If it is showing up here: https://packagecontrol.io/packages/MarkdownPreview, then you *should* be able to install it.  Keep in mind after installation, you may need to restart Sublime (assuming it installs).

Now, if you have it installed and get an error from Markdown Preview, or one of its dependencies, in the console, you can post that here.

**Comment by facelessuser** [comment]
As this is most likely a local system issue, or a package control issue, there is nothing more I can do unless some evidence is presented that leads us to believe Markdown Preview is doing something it shouldn't.

For these reasons, I'm closing this issue.
