### ISSUE TITLE
Javascript language highlighting not working

### ISSUE THREAD

**Issue by pydolan** [facelessuser/MarkdownPreview#64]
It appears that Javascript highlighting is not working in my markdown files:

<img width="454" alt="screen shot 2019-01-18 at 6 32 11 am" src="https://user-images.githubusercontent.com/467780/51390044-552a8f00-1aeb-11e9-868e-5a0e29100043.png">

This differs from what one sees in Github (the below using 'javascript' and 'js'):

```javascript
var s = "JavaScript syntax highlighting";
alert(s);
```
 
```js
var s = "JavaScript syntax highlighting";
alert(s);
```

I'm using v2.2.2 of MarkdownPreview and Sublime v3.1.1 build 3176.  
 I had the default settings for this plugin, but tried setting them to the following, as well as reinstalling the plugin and restarting Sublime: 

```json
{ 
  "github_mode": "gfm", 
  "parser": "github",
  "build_action": "browser",
  "enabled_extensions": [
    "extra", 
    "github", 
    "codehilite(guess_lang=False,pygments_style=github)" 
  ] 
}
```

Is there something I'm missing?

**Comment by facelessuser** [comment]
What am I looking at?  Are you saying that you don't like that the syntax highlighter isn't showing highlighted text?  If so, Markdown Preview doesn't provide a syntax highlighter, you'll have to take that up with whomever provides your Markdown syntax highlighter. Markdown Preview just renders markdown to HTML and shows it in your browser.

**Comment by pydolan** [comment]
Ah, my bad. I assumed this plugin did the in-editor highlighting. Will close
