### ISSUE TITLE
bug(html): permanent links in simple HTML

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/MarkdownPreview#65]
### 1. Summary

If I select `"html_simple": true` in settings, I have problems with permanent links.

### 2. Data

+ `Kira-MarkdownPreview__non-valid-unicode.md`:

```markdown
# Kira

Goddess
```

+ `User/MarkdownPreview.sublime-settings`:

```json
{
    "enabled_parsers": ["markdown"],
    "html_simple": true
}

```

### 3. Steps to reproduce

I reproduce the problem in a version of Sublime Text without plugins and user settings.

For `Kira-MarkdownPreview__non-valid-unicode.md`: <kbd>Ctrl+Shift+P</kbd> (<kbd>⌘⇧p</kbd> for Mac) → `MarkdownPreview: Save to HTML` → I open `Kira-MarkdownPreview__non-valid-unicode.html`.

### 4. Actual behavior

```html
<h1>Kira<a href="#kira" title="Permanent link"></a></h1>
<p>Goddess</p>
```

2 problems.

1. `` ([**U+E157**](http://www.fileformat.info/info/unicode/char/e157/index.htm)) not valid unicode character. Maybe `¶` ([**pilcrow sign**](http://www.fileformat.info/info/unicode/char/b6/index.htm)) do you mean instead?
1. No indent between header and permanent link. Even if pilcrow sign was used, HTML will look like this:

    ![Pilcrow-sign--No_indent](https://i.imgur.com/1mn75y2.png)

### 5. Expected behavior

```html
<h1>Kira <a href="#kira" title="Permanent link">¶</a></h1>
<p>Goddess</p>
```

![Pilcrow_sign--Indent](https://i.imgur.com/qrjjK6R.png)

See also [**real converted HTML example**](https://tuleap.net/plugins/tracker/?aid=12802). Symbol for permanent link does not mix with header text.

![MarkdownPreview__Tuleap](https://i.imgur.com/WW24seH.png)

### 6. Environment

+ Windows 10 Enterprise LTSB 64-bit EN
+ Sublime Text 3.1.1 Build 3176
+ MarkdownPreview 2.2.2

Thanks.

**Comment by hadisfr** [comment]
@facelessuser It's something related to [Python-Markdown](https://github.com/Python-Markdown/markdown).
After running the following lines:
https://github.com/Python-Markdown/markdown/blob/596be577c69c13ac3addcc84701e0a1014b088b0/markdown/extensions/toc.py#L135-L136
```python
        if self.use_permalinks is None:
            self.use_permalinks = config["permalink"]
```
config becomes:
```python
{'slugify': <function slugify at 0x107dd7560>, 'title': '', 'permalink': '\ue157', 'anchorlink': False, 'separator': '-', 'marker': '[TOC]', 'baselevel': '1'}
```
So the [`\ue157`](https://www.fileformat.info/info/unicode/char/e157/index.htm) is printed in:
https://github.com/Python-Markdown/markdown/blob/596be577c69c13ac3addcc84701e0a1014b088b0/markdown/extensions/toc.py#L191
```python
                          else self.use_permalinks)
```
I couldn't find out from where exactly Python-Markdown reads the configs, so could not recognize why this is happening.

**Comment by hadisfr** [comment]
@facelessuser You are right. The same thing happens when `html_simple` is False.
Actually `\ue157` seems to be rendered as link anchor (see [+](http://www.gopureyoga.com/icons.html)). In `html_simple` mode _fontawesome-mini_ font and related css are not loaded, so the actual strange character is shown to the user.

**Comment by facelessuser** [comment]
`html_simple`, as I recall, strips inline style class and IDs. Someone at one time wanted this. I have to see if the current behavior is working as expected.

If rendering is based on something that we are purposely stripping, then there is no problem. If we are stripping or altering something we shouldn't, then we have a problem.

How it is rendering is of little concern as long as the features is doing what it's supposed to.

**Comment by facelessuser** [comment]
@Kristinita, I think I know why you are confused. `html_simple` not only strips out `class`, `id`, and inline `style`, but it does not include HTML headers (including styles).  It gives you just a simple HTML conversion.  Originally someone wanted this for some reason.  They wanted just some simple, raw HTML, and that is what `html_simple` does.

So by default, the Markdown theme uses fontawesome to provide header links.  It does not use Pilcrow:

<img width="220" alt="kira" src="https://user-images.githubusercontent.com/1055125/51547890-6691d500-1e24-11e9-9375-2c68174d534a.png">

In fontawesome, *that* character is known by the value `\ue157`.  This is available in the settings, so you can change it:

```js
        // More default Python Markdown extensions
        {
            "markdown.extensions.toc":
            {
                "permalink": "\ue157"
            }
        },
```

If you prefer Pilcrow, I'd copy the `markdown_extensions` setting to your User settings, and then define Pilcrow:

```js
        // More default Python Markdown extensions
        {
            "markdown.extensions.toc":
            {
                "permalink": "¶"
            }
        },
```

Then, it will be using a character that is not reliant on fontawesome when `html_simple` is used:

<img width="170" alt="kira2" src="https://user-images.githubusercontent.com/1055125/51548713-1b78c180-1e26-11e9-90aa-3d50f1eefbac.png">

If you prefer to strip out `id`, `class`, and/or inline `styles` without stripping out HTML headers, simply configure [`pymdownx.striphtml`](https://facelessuser.github.io/pymdown-extensions/extensions/striphtml/) in your config and don't use `html_simple`.

**Comment by facelessuser** [comment]
Closed as there is no actionable item here.
