### ISSUE TITLE
Could I install MarkdownPreview manually?

### ISSUE THREAD

**Issue by CalanceHao** [facelessuser/MarkdownPreview#66]
I have [trouble](https://github.com/wbond/package_control/issues/1403) using the package control, look like caused by the unreachable server. 
Could I get the .zip of Markdown Preview somewhere and just put it into the /Sublime Text 3/Packages manually?

**Comment by facelessuser** [comment]
You *could*...

It can be quite involved as you also have install dependencies, and I'd be careful to install dependencies from their current tag, not the master branch.  You can use [BracketHighlighter's manual install documentation](http://facelessuser.github.io/BracketHighlighter/installation/#manual-installation) as a general guide, just look at the MarkdownPreview dependency file to get an idea of what dependencies you need for this project.

**Comment by CalanceHao** [comment]
![sublime text 3](https://user-images.githubusercontent.com/11898029/52060287-d92e4d80-25a6-11e9-83fc-0c76d327d6d5.png)
There is a little problem: I can see the setting, but couldn't show the commands. 

My Steps:
0. follow the ' BracketHighlighter's manual install documentation' and the BracketHighlighter can be used.
1. I watch the [dependencies.json](https://github.com/facelessuser/MarkdownPreview/blob/master/dependencies.json). And there are 4 dependencies.
> "pygments",
    "pyyaml",
    "python-markdown",
    "pymdownx"

2. search 'pymdownx' & 'pyyaml' on github, download and renamed them in /Packages.
3. download MarkdownPreview to /Packages.
4. add these code into 00-dependencies.py
```
add_dependency('pyyaml')
add_dependency('pymdownx')
```
5. quit and restart
6. follow the [usage guide](https://facelessuser.github.io/MarkdownPreview/usage/), I cover the user by default and don't change settings.
7. I open ctrl+shift+P,  no `MarkdownPreview:` commands😑

🤦🏻‍♀️Do you know how to solve this problem?
P.S: My sublime version is 3.1.1, Build 3176.

**Comment by facelessuser** [comment]
> search 'pymdownx' & 'pyyaml' on github, download and renamed them in /Packages.

Did you install the packages specifically for Sublime?  The BracketHIighlighter instruction guide actually provided links for some of these packages, but not all of them.  I would be careful and install only the latest release, not directly from the main branch, as the main branch may have unreleased things that should not be installed yet:

- pymdownx (unpack as pymdownx): https://github.com/facelessuser/sublime-pymdownx/releases/tag/1.10.0
- python-markdown (unpack as python-markdown): https://github.com/facelessuser/sublime-markdown/releases/tag/2.6.11
- pygments (unpack as pygments): https://github.com/packagecontrol/pygments/releases/tag/v2.0.2
- pyyaml (unpack as pyyaml): https://github.com/packagecontrol/pyyaml/releases/tag/v3.12.0

> add these code into 00-dependencies.py

Did you forget to add these?

```py
add_dependency('pygments')
add_dependency('python-markdown')
```

**Comment by CalanceHao** [comment]
🎵The Problem is solved and it works as expected😇THX~~~

New operations:
1. I replace these files in your links, and the MarkdownPreview is used the latest [ST3 2.2.2](https://github.com/facelessuser/MarkdownPreview/releases/tag/st3-2.2.2)
![filesinpackages](https://user-images.githubusercontent.com/11898029/52110037-5e167700-263a-11e9-8c05-13ad006a992f.jpg)

2. and I make sure the four dependencies of MarkdownPreview are all write down into the 00-dependencies.py.
![00dependencies](https://user-images.githubusercontent.com/11898029/52110044-6078d100-263a-11e9-8010-0afa9c0b5ec7.jpg)

3. quit and restart

If someone has the same problem hope it will helped😘
