### ISSUE TITLE
Use functionality of this plugin in own python-files

### ISSUE THREAD

**Issue by footballman17** [facelessuser/MarkdownPreview#67]
I want use functionality of this plugin for converting md-files **in my own python-files**. For example, such as python-lib. Сan I do that? Thanks-)

**Comment by facelessuser** [comment]
I'm not exactly sure what you mean. Are you talking about a non Sublime plugin project? Like outside the Sublime environment?

**Comment by footballman17** [comment]
Yes, outside the Sublime environment in own python-script

**Comment by facelessuser** [comment]
You could adapt it. Currently the commands are set up to use the Sublime API library, which obviously won't be available outside of Sublime, but all the non-Sublime code should work, assuming you install the appropriate dependencies.

It won't work out of the box though, you'll have to make some modifications.

**Comment by footballman17** [comment]
Ok, thanks

**Comment by facelessuser** [comment]
Closed as the question was answered.
