### ISSUE TITLE
Is it possible to get an outline view of the document?

### ISSUE THREAD

**Issue by tifDev** [facelessuser/MarkdownPreview#71]

**Comment by facelessuser** [comment]
I'm not sure what this is requesting. If you can provide more detailed information, maybe I can answer this question.

**Comment by tifDev** [comment]
Something like this: https://i.redd.it/6ktb0j6jvci21.png

**Comment by facelessuser** [comment]
I'm afraid this is beyond the scope of what is planned for MarkdownPreview.
