### ISSUE TITLE
Sublime freezes while previewing in qutebrowser or surf

### ISSUE THREAD

**Issue by lairdchris** [facelessuser/MarkdownPreview#72]
When I set qutebrowser or surf (suckless.org)  as browser, Sublime freezes until I close the preview again.
Setting it to vivaldi works as expected.

My configuration:
Ubuntu 18.10, Sublime Build 3176, MarkdownPreview 2.2.2

**Comment by diffficult** [comment]
same issue with `surf`

```
{
	/*
	    Sets the default opener for HTML files

	    default - Use the system default HTML viewer
	    other - Set a full path to any executable. ex: /Applications/Google Chrome Canary.app or /Applications/Firefox.app
	*/
	"browser": "/usr/local/bin/surf",
}
```

**Comment by diffficult** [comment]
Still not working with `surf`, Sublime still freezed in the background til you close browser window displaying preview. Other than that preview looks fine and file is created where it was supposed to or using the path in your config file.

**Comment by facelessuser** [comment]
@diffficult, I'm confused, are you saying that @lairdchris's [pull request](https://github.com/facelessuser/MarkdownPreview/pull/73) doesn't fix your issue? The issue was closed because @lairdchris open a pull request that addresses the issue.

**Comment by diffficult** [comment]
@facelessuser I'm sorry, I thougth this was already reflected after updating the package with Package Control

**Comment by facelessuser** [comment]
No, I didn't even close this issue.  I usually don't close an issue until the fix is merged, and even then releases don't always happen right after I merge a fix.

I'll reopen this for now as I haven't merged the fix yet.

**Comment by facelessuser** [comment]
So the reason for this issue is because this project, before my time, was written for ST2. ST3 support was added, but clearly not tested in great detail as the `linux2` worked in ST2 which ran on Python 2.6. But this was convention of including Linux major version was discontinued in Python 3.3 which ST3 relies on.

**Comment by lairdchris** [comment]
Sorry for the confusion. The issue was autoclosed because of my reference in the commit comment...
I'm new to this pull request business ;-)

**Comment by facelessuser** [comment]
Usually GitHub doesn't autoclose until the pull is merged, but it's no big deal.
