### ISSUE TITLE
LiveReload script fails to load on Firefox

### ISSUE THREAD

**Issue by O-J1** [facelessuser/MarkdownPreview#74]
**Firefox:** 65.0.2
**Sublime:** 3.1.1, Build 3176
**OS:** Windows 10 (Version 10.0.17134.590)
**Markdown Preview:** Installed through Package Control
**Live Reload:** Installed through Package Control
**Live Reload Broweser Plugin:** https://github.com/twolfson/livereload-extensions

---

Live reload does not work on Firefox when try to use it with Markdown Preview. Livereload **is** enabled and I have followed the [documentation](https://facelessuser.github.io/MarkdownPreview/usage/#livereload) and I am just using the plain old markdown parser, nothing fancy.

When checking the console for the generated file, "loading failed for <script> ... " appears in the console: 
![image](https://user-images.githubusercontent.com/18110006/53953962-e8b23080-4128-11e9-985b-d09673969b40.png)

All of my browser plugins are disabled on localhost files and live reload works when I normally insert the below snippet into a HTML document: 
`<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>`

The generated file markdown file uses async (it was mentioned in past issues as a fix for chrome?).  Definitely not what is used/working on firefox. Unsure of how to modify it myself to correct what this plugin inserts

Thanks for the wonderful plugin.

Regards,
Xam

**Comment by facelessuser** [comment]
Supposedly the latest fix was tested in Firefox. It looks like it was tested specifically in macOS, not Windows. I'll have to try and confirm whether it works myself. I'll let you know when I have a chance to confirm.

**Comment by Algomorph** [comment]
Hi, thank you for this useful plugin!

I'm having a similar issue with **Chrome** 85.0.4183.102, not sure if it's duplicate, so I'll write here first.
I also followed the [official instructions](https://facelessuser.github.io/MarkdownPreview/usage/#livereload). LiveReload seems to reload the page when I save the file in Sublime, but the content isn't updated (and neither is the actual generated html on disk).

**Sublime**: 3.2.2
**Markdown Preview**: installed from Package Control just today (2.2.5?)
**OS**: Ubuntu 18.04.5 LTS
**LiveReload**: installed from Package Control.

**Comment by facelessuser** [comment]
LiveReload has always been a pain, and can honestly be finicky. It is the solution that I inherited with the project when I took it over. TBH, I don't often use the live reload feature, but I'm glad you got it working.

If it helps, I do accept pull requests for documentation updates. But if no one makes one, I'll try and look at sometime later and see if we can improve the docs a bit.
