### ISSUE TITLE
Rendering is picky about list indentation

### ISSUE THREAD

**Issue by lgierth** [facelessuser/MarkdownPreview#76]
First off, hat tip for this package, I'm really happy a simple Ctrl+B gives me a rendered preview in my browser.

I've noticed that 2-space list indentation isn't recognized, and I need to make it 4-space to actually render these list items as children. Github would probably render these correctly, but I'd prefer to keep things local and not depend on an Internet connection.

My only custom config is
```json
{
  "build_action": "browser"
}
```
so the `parser` is `markdown` and the `markdown_extensions` are left with their default.

**Comment by lgierth** [comment]
These files are `UTF-8` and `Spaces: 2` in Sublime.

**Comment by facelessuser** [comment]
Sorry that I missed this.

That is simply the way Python Markdown does things. You can use the github or gitlab parser if it is not to your liking, or possibly look for a Python Markdown extension that treats things differently and integrate it into Sublime to use it.

**Comment by lgierth** [comment]
Understood, thanks! I also noticed a few other spots where Python Markdown seems to be a little stricter.

I'll probably just live with it :)
