### ISSUE TITLE
Github Style not working

### ISSUE THREAD

**Issue by DiggidyDale** [facelessuser/MarkdownPreview#8]
Hi,

Randomly yesterday MarkdownPreview stopped working with the GitHub style. When I preview or save in the github style, it just stalls, then mingw64 with curl.exe opens and after a bit, a new tab in Firefox opens but it is blank with just the stylised box. There is no contents from my actual md file.

I am running on sublime3, windows 10.

I have attached the md and the created HTML in case its helpful.
[Markdown.zip](https://github.com/facelessuser/MarkdownPreview/files/2008391/Markdown.zip)

**Comment by facelessuser** [comment]
Unfortunately you are going to have to give some more details.  Are you getting errors in the console.  I recently released a new major version with some breaking settings.  Check out the docs to see what changed and what you need to change in your own settings.

If you can provide some error report from the console, maybe that will give some insight.

**Comment by DiggidyDale** [comment]
I am not getting any errors in the console that is the weird thing. Is there any way to turn on logging?

**Comment by facelessuser** [comment]
I'd try and uninstall make sure there is no folder `MarkdownPreview` or `Markdown Preview` (old name) in you `Packages` directory.  Also make sure in `Installed Packages` there is no `sublime-package` file called `MarkdownPreview` or `Markdown Preview` either.  Then reinstall, restart, and see if it is working for you.

**Comment by zsiegel92** [comment]
I will open a new issue, but for anyone else wondering how to adjust to this update, here's a fix.

Add the following to your MarkdownPreview User Settings dict:

	"js": [
			"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js",
			        "res://MarkdownPreview/js/math_config.js",
		],
		"markdown_extensions": {
		        "pymdownx.arithmatex": {
		            "generic": true
		        }
		    }

**Comment by facelessuser** [comment]
No response for 18 days. Closing.
