### ISSUE TITLE
Please add a requirements.txt

### ISSUE THREAD

**Issue by Mrigyen** [facelessuser/MarkdownPreview#82]
It is really hard to know which `pip` package to install to get the `import sublime` line working, for example. It would help a lot if you would make a `requirements.txt` so installing all necessary dependencies would be easy so that one can start working on this project immediately.

**Comment by facelessuser** [comment]
This cannot be installed with `pip`. This is a Sublime Text plugin requiring installation within Sublime Text. Dependencies are listed here: https://github.com/facelessuser/MarkdownPreview/blob/master/dependencies.json.

I would `git clone` into your `Packages` folder and try running Package Control's `Satisfy Dependencies` command (restarting when done).

If you don't use Sublime Text then this repository is probably not for you.

**Comment by Mrigyen** [comment]
My aim was to isolate the working components so it can run from the command line. 

This was so that I can use this with vim. 

I understand if you don't want to help out. I guess I'll have to build it from scratch using `python-markdown` and `pygments`.

**Comment by facelessuser** [comment]
Unfortunately, you can't get the `sublime` requirement except from Sublime Text, and if you did, it would be functionally useless without stubbing and mocking. You are free to create a requirements text for your personal use from the linked dependencies.json. All of those relate to actual packages that should be found on `pip`. 

I support enough things already, so I won't be able to offer additional help for a platform that I don't use.
