### ISSUE TITLE
Auto enable LiveReload plugins?

### ISSUE THREAD

**Issue by jfcherng** [facelessuser/MarkdownPreview#84]
https://facelessuser.github.io/MarkdownPreview/usage/#livereload

Is it possible to make the following steps become automatic? Currently, I have to do this every time after ST is closed.

```
- Open the command palette and select the command LiveReload: Enable/disable plug-ins.
- Select Simple Reload with delay (400ms). It is possible you can get away with Simple Reload, but some experience an issue where they are one rev behind when using Simple Reload.
```

**Comment by facelessuser** [comment]
I have no automated system in place. To be honest, that sounds like something that should be implemented in LiveReload, not here. Maybe that have something you can configure to do this? I haven't looked yet.

**Comment by jfcherng** [comment]
Thanks. I get it to work automatically with a [PR](https://github.com/alepez/LiveReload-sublimetext3/pull/16) to LiveReload. :v:
