### ISSUE TITLE
Live Preview in Sublime

### ISSUE THREAD

**Issue by mauroreisvieira** [facelessuser/MarkdownPreview#86]
Is not possible show the Markdown Preview in Sublime Text Tab?

Like VSCode do:

![28495106-30b3b15e-6f09-11e7-8eb6-ca4ca001ab15](https://user-images.githubusercontent.com/3084774/62049644-97a1f680-b207-11e9-9ba3-d07c7b81877f.png)

---

[Example other plugin for Sublime](https://github.com/math2001/MarkdownLivePreview)

**Comment by facelessuser** [comment]
Sublime's internal HTML renderer is extremely limited. It could be done, but you'd be extremely disappointed in it's output. If your aim was to render it like it will actually appear.

Thinks like math wouldn't render at all as those are done by JavaScript. That is just one example though.

**Comment by mauroreisvieira** [comment]
Ok. Thanks for you fast answer.

**Comment by facelessuser** [comment]
You can do the basics though as I do here: https://github.com/facelessuser/sublime-markdown-popups. You are just limited.
