### ISSUE TITLE
How to display local images?

### ISSUE THREAD

**Issue by qijimrc** [facelessuser/MarkdownPreview#89]
I am using Mac OS and Sublime Text3.

When I typed `![alt]("/Users/HostName/path/to/SomePicture.png")` in the markdown text, the plugin didn't help me successfully display the image.

Is the way I use it wrong?

**Comment by facelessuser** [comment]
You should be using the syntax found here: https://daringfireball.net/projects/markdown/syntax#img.

**Comment by qijimrc** [comment]
> You should be using the syntax found here: https://daringfireball.net/projects/markdown/syntax#img.

Hi @facelessuser , thank you for your reply.
Sorry, my description is not accurate and I have made changes. I did use the correct syntax, but I still can't display the image.
This problem has been bothering me for a long time and I have been unable to find the reason.

**Comment by facelessuser** [comment]
Unfortunately I would need a reproducible example to help. I'm afraid I'm having a difficult time understanding the problem you are describing.

**Comment by facelessuser** [comment]
Unfortunately, without more information, I cannot answer this question. Images are working just fine for me, and I've heard of no other related complaints. Closing this issue.
