### ISSUE TITLE
macOS Keybinding

### ISSUE THREAD

**Issue by dialectstudio** [facelessuser/MarkdownPreview#91]
HI, what is the keybinding for macOS?

**Comment by facelessuser** [comment]
There aren't really any key bindings per se. There is like a build environment for markdown files. So when you run the default build shortcut while in a Markdown file, it will convert the file to HTML.

Normally, you'd just use the command palette and pick the `Markdown Preview: Preview in Browser` option. My best advise is to check out the documentation: https://facelessuser.github.io/MarkdownPreview/usage/.
