### ISSUE TITLE
Key binding not working when parser selected

### ISSUE THREAD

**Issue by rigwild** [facelessuser/MarkdownPreview#94]
Hello,

I noticed that when you enable only one parser in your configuration file:
```json
{
  "enabled_parsers": ["markdown"]
}
```

And you create a key binding like the following:
```json
[
  { "keys": ["ctrl+alt+b"], "command": "markdown_preview_select", "args": {"target": "browser", "parser":"markdown"} }
]
```

Nothing happens when you hit the keyboard shortcut.

I fixed it by not specifying the parser in the key binding but that was not obvious to understand.
```json
[
  { "keys": ["ctrl+alt+b"], "command": "markdown_preview_select", "args": {"target": "browser"} }
]
```

Maybe it should be fixed (if doable without huge changes), or at least specified in the documentation.

Have a nice day :grinning:

**Comment by facelessuser** [comment]
That command doesn't take a parser argument: https://github.com/facelessuser/MarkdownPreview/blob/master/markdown_preview.py#L995.

It didn't run most likely because it was throwing an error for to too many arguments being passed.

**Comment by rigwild** [comment]
My bad, I copy pasted from https://facelessuser.github.io/MarkdownPreview/usage/#to-preview

Did not see it was not the same command in the examples.

**Comment by facelessuser** [comment]
No worries :).
